In [2]:
import pandas as pd # import pandas as module object pd

In [3]:
"""
df = pd.read_csv('Company_Census_File_20260701.csv')
df.head()
"""
# To avoid a warning message for mixed data/variables inside Series obj (columns), let's use the next line of code:
df = pd.read_csv("Company_Census_File_20260701.csv", low_memory=False) # 'low_memory=False' tells Pandas: "Read the file first, then determine the data types."
df.head()

,MCS150_DATE,ADD_DATE,STATUS_CODE,DOT_NUMBER,DUN_BRADSTREET_NO,PHY_OMC_REGION,SAFETY_INV_TERR,CARRIER_OPERATION,BUSINESS_ORG_ID,MCS150_MILEAGE,...,TRPSCHOOL_16,TRPBUS_16,TRPVAN_1_8,TRPVAN_9_15,TRPLIMO_1_8,TRPLIMO_9_15,TRPLIMO_16,DOCKET1_STATUS_CODE,DOCKET2_STATUS_CODE,DOCKET3_STATUS_CODE
0,20260501 2225,19861230,A,284500,0.0,4.0,E,A,3.0,30000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN
1,20260127 1620,19861230,A,284518,107616187.0,5.0,E,A,3.0,1042863.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN
2,20250409 1710,19861230,A,284519,NaN,9.0,D,A,3.0,300000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN
3,20250417 0000,19861230,A,284585,826568917.0,5.0,A,A,3.0,308700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN
4,20260508 1536,19861230,A,284600,608747820.0,5.0,A,A,3.0,16743901.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 611057 entries, 0 to 611056
Columns: 147 entries, MCS150_DATE to DOCKET3_STATUS_CODE
dtypes: float64(71), int64(7), str(69)
memory usage: 685.3 MB

In [5]:
# Sort columns alphabetically from A to Z
df = df.sort_index(axis=1) # 'axis=0' for rows, 'axis=1' for columns

In [6]:
pd.set_option('display.max_columns', 147) # We could also use None as a second argument to display all columns even without knowing their total number, but since we know the total number of columns, then that would not be necessary
df.head(10)

,ADD_DATE,AVG_DRIVERS_LEASED_PER_MONTH,BUSINESS_ORG_DESC,BUSINESS_ORG_ID,BUS_UNITS,CARRIER_MAILING_CITY,CARRIER_MAILING_CNTY,CARRIER_MAILING_COUNTRY,CARRIER_MAILING_STATE,CARRIER_MAILING_STREET,CARRIER_MAILING_UND_DATE,CARRIER_MAILING_ZIP,CARRIER_OPERATION,CARSHIP,CELL_PHONE,CLASSDEF,COMPANY_OFFICER_1,COMPANY_OFFICER_2,CRGO_BEVERAGES,CRGO_BLDGMAT,CRGO_CARGOOTHR,CRGO_CARGOOTHR_DESC,CRGO_CHEM,CRGO_COALCOKE,CRGO_COLDFOOD,CRGO_CONSTRUCT,CRGO_DRIVETOW,CRGO_DRYBULK,CRGO_FARMSUPP,CRGO_GARBAGE,CRGO_GENFREIGHT,CRGO_GRAINFEED,CRGO_HOUSEHOLD,CRGO_INTERMODAL,CRGO_LIQGAS,CRGO_LIVESTOCK,CRGO_LOGPOLE,CRGO_MACHLRG,CRGO_MEAT,CRGO_METALSHEET,CRGO_MOBILEHOME,CRGO_MOTOVEH,CRGO_OILFIELD,CRGO_PAPERPROD,CRGO_PASSENGERS,CRGO_PRODUCE,CRGO_USMAIL,CRGO_UTILITY,CRGO_WATERWELL,DBA_NAME,DOCKET1,DOCKET1PREFIX,DOCKET1_STATUS_CODE,DOCKET2,DOCKET2PREFIX,DOCKET2_STATUS_CODE,DOCKET3,DOCKET3PREFIX,DOCKET3_STATUS_CODE,DOT_NUMBER,DRIVER_INTER_TOTAL,DUN_BRADSTREET_NO,EMAIL_ADDRESS,FAX,FLEETSIZE,HM_Ind,INTERSTATE_BEYOND_100_MILES,INTERSTATE_WITHIN_100_MILES,INTRASTATE_BEYOND_100_MILES,INTRASTATE_WITHIN_100_MILES,LEGAL_NAME,MAIL_BARRIO,MAIL_NATIONALITY_INDICATOR,MCS150_DATE,MCS150_MILEAGE,MCS150_MILEAGE_YEAR,MCS150_UPDATE_CODE_ID,MCS151_MILEAGE,MCSIPDATE,MCSIPSTEP,OWNBUS_16,OWNCOACH,OWNLIMO_16,OWNLIMO_1_8,OWNLIMO_9_15,OWNSCHOOL_16,OWNSCHOOL_1_8,OWNSCHOOL_9_15,OWNTRACT,OWNTRAIL,OWNTRUCK,OWNVAN_1_8,OWNVAN_9_15,PHONE,PHY_BARRIO,PHY_CITY,PHY_CNTY,PHY_COUNTRY,PHY_NATIONALITY_INDICATOR,PHY_OMC_REGION,PHY_STATE,PHY_STREET,PHY_ZIP,POINTNUM,POWER_UNITS,PRIOR_REVOKE_DOT_NUMBER,PRIOR_REVOKE_FLAG,RECORDABLE_CRASH_RATE,REVIEW_DATE,REVIEW_ID,REVIEW_TYPE,SAFETY_INV_TERR,SAFETY_RATING,SAFETY_RATING_DATE,STATUS_CODE,TOTAL_CARS,TOTAL_CDL,TOTAL_DRIVERS,TOTAL_INTRASTATE_DRIVERS,TRMBUS_16,TRMCOACH,TRMLIMO_16,TRMLIMO_1_8,TRMLIMO_9_15,TRMSCHOOL_16,TRMSCHOOL_1_8,TRMSCHOOL_9_15,TRMTRACT,TRMTRAIL,TRMTRUCK,TRMVAN_1_8,TRMVAN_9_15,TRPBUS_16,TRPCOACH,TRPLIMO_16,TRPLIMO_1_8,TRPLIMO_9_15,TRPSCHOOL_16,TRPSCHOOL_1_8,TRPSCHOOL_9_15,TRPTRACT,TRPTRAIL,TRPTRUCK,TRPVAN_1_8,TRPVAN_9_15,TRUCK_UNITS,UNDELIV_PHY
0,19861230,NaN,CORPORATION,3.0,0.0,RED OAK,127,US,NC,PO BOX 206,NaN,27868,A,C,NaN,AUTHORIZED FOR HIRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C N TRUCKING COMPANY,194609.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284500,1.0,0.0,mcgeetrucking@gmail.com,NaN,A,N,1.0,0.0,0.0,0.0,MCGEE TRUCKING CO INC,NaN,NaN,20260501 2225,30000.0,2025.0,3.0,NaN,20221203.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,2.529082e+09,NaN,NASHVILLE,127,US,NaN,4.0,NC,7868 STONEY CREEK LN,27856,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,NaN,A,NaN,1.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
1,19861230,0.0,CORPORATION,3.0,0.0,FRANKLIN,165,US,OH,8251 CLAUDE THOMAS RD,NaN,45005-1412,A,C,NaN,AUTHORIZED FOR HIRE,ROBERT MASCHMEIER,RITA MASCHMEIER,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194817.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284518,14.0,107616187.0,ROBM@BMTINC.US,9377437738,I,N,14.0,0.0,0.0,0.0,BOBS MORAINE TRUCKING INC,NaN,NaN,20260127 1620,1042863.0,2025.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,24.0,NaN,NaN,NaN,9.377468e+09,NaN,FRANKLIN,165,US,NaN,5.0,OH,8251 CLAUDE THOMAS RD,45005-1412,NaN,20,NaN,N,NaN,19991105.0,NaN,C,E,S,20000218.0,A,NaN,14.0,14.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,NaN
2,19861230,0.0,CORPORATION,3.0,0.0,SLC,35,US,UT,1989 SOUTH 4130 WEST UNIT D,NaN,84104,A,C,8.016605e+09,AUTHORIZED FOR HIRE,DEBORAH DUFFY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184764.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284519,4.0,NaN,debbiedms@ymail.com,8018877835,B,N,1.0,3.0,0.0,NaN,DESIGNER MOVING AND STORAGE INC,NaN,NaN,20250409 1710,300000.0,2024.0,2.0,NaN,20171115.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,8.018878e+09,NaN,SLC,35,US,NaN,9.0,UT,1989 SOUTH 4130 WEST UNIT D,84104,NaN,2,NaN,N,NaN,19900614.0,NaN,S,D,S,19901023.0,A,NaN,0.0,4.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
3,19861230,NaN,CORPORATION,3.0,0.0,LANSING,31,US,IL,1865 BERNICE ROAD SUITE 1,NaN,60438,A,C,NaN,AUTHORIZED FOR HIRE,THOMAS RONDINELLI,MATTHEW T MENDER,NaN,NaN,X,ROOFING MATERIAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181429.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284585,13.0,826568917.0,matt@rownexpress.com,7088891576,F,N,2.0,11.0,0.0,0.0,R-OWN EXPRESS INC,NaN,NaN,20250417 0000,308700.0,2024.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.088891e+09,NaN,LANSING,31,US,NaN,5.0,IL,1865 BERNICE ROAD SUITE 1,60438,NaN,13,NaN,NaN,NaN,20051229.0,NaN,C,A,S,20060216.0,A,NaN,13.0,13.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,NaN
4,19861230,NaN,CORPORATION,3.0,0.0,SUMMIT,31,US,IL,5450 S CENTER AVENUE,NaN,60501,A,C,NaN,AUTHORIZED FOR HIRE,NaN,NaN,NaN,NaN,X,FOOD LIQUID BULK,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,194782.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284600,160.0,608747820.0,mattn@jkctrucking.com,7089241148,Q,N,128.0,32.0,0.0,0.0,JKC TRUCKING INC,NaN,NaN,20260508 1536,16743901.0,2025.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,370.0,NaN,NaN,NaN,7.084964e+09,NaN,SUMMIT,31,US,NaN,5.0,IL,5450 S CENTER AVENUE,60501,NaN,190,NaN,NaN,NaN,20110225.0,NaN,C,A,S,20110303.0,A,NaN,160.0,160.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180,NaN
5,19861230,0.0,CORPORATION,3.0,13.0,GURNEE,97,US,IL,PO BOX 514,NaN,60031,A,C,NaN,AUTHORIZED FOR HIRE,ROBERT OLSON,RAYMOND OLSON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,MIDWEST MOTOR COACH,194678.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284606,16.0,NaN,RAY@OLSONTRANSPORTATION.COM,NaN,F,N,16.0,0.0,0.0,0.0,ROBERT M OLSON,NaN,NaN,20250726 1320,192416.0,2024.0,1.0,NaN,20090522.0,0.0,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.473361e+09,NaN,GURNEE,97,US,NaN,5.0,IL,1082 FERNDALE ST,60031,NaN,13,NaN,N,NaN,20241125.0,2189503.0,C,A,S,20241203.0,A,NaN,16.0,16.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
6,19861230,0.0,CORPORATION,3.0,0.0,DAYTON,19,US,NV,PO BOX 788,NaN,89403,A,C,7.757422e+09,AUTHORIZED FOR HIRE,RON BARKER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193131.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284614,1.0,NaN,ronbarker1182@yahoo.com,NaN,A,N,NaN,1.0,0.0,0.0,RON BARKER LLC,NaN,NaN,20250224 1207,32580.0,2024.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,NaN,NaN,NaN,7.757422e+09,NaN,DAYTON,19,US,NaN,9.0,NV,182 RING ROAD,89403,NaN,1,NaN,N,NaN,19890210.0,NaN,S,H,S,19891025.0,A,NaN,1.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
7,19861230,0.0,CORPORATION,3.0,0.0,CHICAGO HEIGHTS,31,US,IL,1800 EAST JOE ORR ROAD,NaN,60411,A,C,7.088781e+09,AUTHORIZED FOR HIRE,DALE OLTHOFF,NaN,NaN,NaN,X,STONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193397.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284615,1.0,NaN,cherylf@olthoffinc.com,NaN,A,N,NaN,1.0,NaN,NaN,OLTHOFF INC,NaN,NaN,20260306 0000,14640.0,2025.0,3.0,NaN,20160127.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,7.087587e+09,NaN,CHICAGO HEIGHTS,31,US,NaN,5.0,IL,1800 EAST JOE ORR ROAD,60411,NaN,1,NaN,N,NaN,NaN,NaN,NaN,A,NaN,NaN,A,NaN,1.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
8,19861230,0.0,CORPORATION,3.0,14.0,TYLER,423,US,TX,181 CR 313E,NaN,75706,A,C,9.035301e+09,AUTHORIZED FOR HIRE,CHARLES P ROACH,SHERYLL JEAN ROACH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,193135.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284654,10.0,144905015.0,jean@chuckstravel.com,NaN,F,N,10.0,0.0,NaN,0.0,CHUCK'S TRAVEL COACHES INC,NaN,NaN,20260422 1515,945621.0,2025.0,3.0,NaN,20150612.0,0.0,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.035975e+09,NaN,TYLER,423,US,NaN,6.0,TX,181 CR 313E,75706,NaN,14,NaN,N,NaN,20230630.0,2031455.0,C,D,S,20240131.0,A,NaN,10.0,10.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
9,19861230,0.0,CORPORATION,3.0,0.0,BELLMAWR,7,US,NJ,PO BOX 845,NaN,08099,A,C,NaN,AUTHORIZED FOR HIRE,DAN SZUSTOWICZ,LISA COLELLA,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173086.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,284686,2.0,NaN,DAN@Dandminc.com,8569630404,C,N,2.0,0.0,0.0,0.0,D & M TRANSPORTATION SERVICES INC,NaN,NaN,20251212 1110,95031.0,2024.0,1.0,NaN,20101211.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,NaN,NaN,NaN,8.569630e+09,NaN,CAMDEN,7,US,NaN,1.0,NJ,2500 BROADWAY-BLDG I,08104,NaN,4,NaN,N,NaN,NaN,NaN,NaN,W,NaN,NaN,A,NaN,2.0,2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN

In [7]:
# What columns' info/names do we have?
pd.set_option('display.max_seq_items', None) # to display all sequential items (from for example 'df.columns'), None --> removes any display limit entirely
df.columns

Index(['ADD_DATE', 'AVG_DRIVERS_LEASED_PER_MONTH', 'BUSINESS_ORG_DESC',
       'BUSINESS_ORG_ID', 'BUS_UNITS', 'CARRIER_MAILING_CITY',
       'CARRIER_MAILING_CNTY', 'CARRIER_MAILING_COUNTRY',
       'CARRIER_MAILING_STATE', 'CARRIER_MAILING_STREET',
       'CARRIER_MAILING_UND_DATE', 'CARRIER_MAILING_ZIP', 'CARRIER_OPERATION',
       'CARSHIP', 'CELL_PHONE', 'CLASSDEF', 'COMPANY_OFFICER_1',
       'COMPANY_OFFICER_2', 'CRGO_BEVERAGES', 'CRGO_BLDGMAT', 'CRGO_CARGOOTHR',
       'CRGO_CARGOOTHR_DESC', 'CRGO_CHEM', 'CRGO_COALCOKE', 'CRGO_COLDFOOD',
       'CRGO_CONSTRUCT', 'CRGO_DRIVETOW', 'CRGO_DRYBULK', 'CRGO_FARMSUPP',
       'CRGO_GARBAGE', 'CRGO_GENFREIGHT', 'CRGO_GRAINFEED', 'CRGO_HOUSEHOLD',
       'CRGO_INTERMODAL', 'CRGO_LIQGAS', 'CRGO_LIVESTOCK', 'CRGO_LOGPOLE',
       'CRGO_MACHLRG', 'CRGO_MEAT', 'CRGO_METALSHEET', 'CRGO_MOBILEHOME',
       'CRGO_MOTOVEH', 'CRGO_OILFIELD', 'CRGO_PAPERPROD', 'CRGO_PASSENGERS',
       'CRGO_PRODUCE', 'CRGO_USMAIL', 'CRGO_UTILITY', 'CRGO_WATERWELL',
       'DBA_NAME', 'DOCKET1', 'DOCKET1PREFIX', 'DOCKET1_STATUS_CODE',
       'DOCKET2', 'DOCKET2PREFIX', 'DOCKET2_STATUS_CODE', 'DOCKET3',
       'DOCKET3PREFIX', 'DOCKET3_STATUS_CODE', 'DOT_NUMBER',
       'DRIVER_INTER_TOTAL', 'DUN_BRADSTREET_NO', 'EMAIL_ADDRESS', 'FAX',
       'FLEETSIZE', 'HM_Ind', 'INTERSTATE_BEYOND_100_MILES',
       'INTERSTATE_WITHIN_100_MILES', 'INTRASTATE_BEYOND_100_MILES',
       'INTRASTATE_WITHIN_100_MILES', 'LEGAL_NAME', 'MAIL_BARRIO',
       'MAIL_NATIONALITY_INDICATOR', 'MCS150_DATE', 'MCS150_MILEAGE',
       'MCS150_MILEAGE_YEAR', 'MCS150_UPDATE_CODE_ID', 'MCS151_MILEAGE',
       'MCSIPDATE', 'MCSIPSTEP', 'OWNBUS_16', 'OWNCOACH', 'OWNLIMO_16',
       'OWNLIMO_1_8', 'OWNLIMO_9_15', 'OWNSCHOOL_16', 'OWNSCHOOL_1_8',
       'OWNSCHOOL_9_15', 'OWNTRACT', 'OWNTRAIL', 'OWNTRUCK', 'OWNVAN_1_8',
       'OWNVAN_9_15', 'PHONE', 'PHY_BARRIO', 'PHY_CITY', 'PHY_CNTY',
       'PHY_COUNTRY', 'PHY_NATIONALITY_INDICATOR', 'PHY_OMC_REGION',
       'PHY_STATE', 'PHY_STREET', 'PHY_ZIP', 'POINTNUM', 'POWER_UNITS',
       'PRIOR_REVOKE_DOT_NUMBER', 'PRIOR_REVOKE_FLAG', 'RECORDABLE_CRASH_RATE',
       'REVIEW_DATE', 'REVIEW_ID', 'REVIEW_TYPE', 'SAFETY_INV_TERR',
       'SAFETY_RATING', 'SAFETY_RATING_DATE', 'STATUS_CODE', 'TOTAL_CARS',
       'TOTAL_CDL', 'TOTAL_DRIVERS', 'TOTAL_INTRASTATE_DRIVERS', 'TRMBUS_16',
       'TRMCOACH', 'TRMLIMO_16', 'TRMLIMO_1_8', 'TRMLIMO_9_15', 'TRMSCHOOL_16',
       'TRMSCHOOL_1_8', 'TRMSCHOOL_9_15', 'TRMTRACT', 'TRMTRAIL', 'TRMTRUCK',
       'TRMVAN_1_8', 'TRMVAN_9_15', 'TRPBUS_16', 'TRPCOACH', 'TRPLIMO_16',
       'TRPLIMO_1_8', 'TRPLIMO_9_15', 'TRPSCHOOL_16', 'TRPSCHOOL_1_8',
       'TRPSCHOOL_9_15', 'TRPTRACT', 'TRPTRAIL', 'TRPTRUCK', 'TRPVAN_1_8',
       'TRPVAN_9_15', 'TRUCK_UNITS', 'UNDELIV_PHY'],
      dtype='str')

In [8]:
# Filter our data for only the state of Texas:
filt_df = (df[df['PHY_STATE'] == 'TX'])
len(filt_df) # the len(...) function calculates the number of rows in a ... df argument ('filt_df' in this case)

48577

In [9]:
# FLEETSIZE: (AI recommendation)
# O	56–75	✅ Include
# P	76–100	✅ Include
# Q	101–200	⭐ Include
# R	201–300	⭐ Include
# S	301–400	⭐ Include
# T	401–550	✅ Include

# Use the .isin() method with our refered filt_df Series obj 'FLEETSIZE' data/values (filt_df['FLEETSIZE']) with a list argument including all the information we want our new filtered to have, therefore avoiding using the or '|' operator many times
filt_df = (filt_df[filt_df["FLEETSIZE"].isin(["O", "P", "Q", "R", "S", "T"])])
len(filt_df)

722

In [10]:
# filter to remove any rows with positive 'BUS_UNITS' column values whle keeping also NaN values (Not a Number)
# filt structure: df = (df[(df[]...) | (df[]...)])
filt_df = (filt_df[(filt_df['BUS_UNITS'] <= 0) | (filt_df['BUS_UNITS'].isna())]) # the method .isna() would include the NaN values four our df['Column'] reference data
len(filt_df)

695

In [11]:
# POWER_UNITS = Straight trucks + truck tractors + buses
# Since Cruze focuses on Class 8 truck fleets (heaviest commercial vehicles) then we should be working on 'POWER_UNITS', which covers truck tractors data

# descending sort of 'POWER_UNITS' data/values
filt_df = filt_df.sort_values(by='POWER_UNITS', ascending=False) # 'ascending=True' --> ascending by default, 'ascending=False' --> descending
filt_df.head(30)

,ADD_DATE,AVG_DRIVERS_LEASED_PER_MONTH,BUSINESS_ORG_DESC,BUSINESS_ORG_ID,BUS_UNITS,CARRIER_MAILING_CITY,CARRIER_MAILING_CNTY,CARRIER_MAILING_COUNTRY,CARRIER_MAILING_STATE,CARRIER_MAILING_STREET,CARRIER_MAILING_UND_DATE,CARRIER_MAILING_ZIP,CARRIER_OPERATION,CARSHIP,CELL_PHONE,CLASSDEF,COMPANY_OFFICER_1,COMPANY_OFFICER_2,CRGO_BEVERAGES,CRGO_BLDGMAT,CRGO_CARGOOTHR,CRGO_CARGOOTHR_DESC,CRGO_CHEM,CRGO_COALCOKE,CRGO_COLDFOOD,CRGO_CONSTRUCT,CRGO_DRIVETOW,CRGO_DRYBULK,CRGO_FARMSUPP,CRGO_GARBAGE,CRGO_GENFREIGHT,CRGO_GRAINFEED,CRGO_HOUSEHOLD,CRGO_INTERMODAL,CRGO_LIQGAS,CRGO_LIVESTOCK,CRGO_LOGPOLE,CRGO_MACHLRG,CRGO_MEAT,CRGO_METALSHEET,CRGO_MOBILEHOME,CRGO_MOTOVEH,CRGO_OILFIELD,CRGO_PAPERPROD,CRGO_PASSENGERS,CRGO_PRODUCE,CRGO_USMAIL,CRGO_UTILITY,CRGO_WATERWELL,DBA_NAME,DOCKET1,DOCKET1PREFIX,DOCKET1_STATUS_CODE,DOCKET2,DOCKET2PREFIX,DOCKET2_STATUS_CODE,DOCKET3,DOCKET3PREFIX,DOCKET3_STATUS_CODE,DOT_NUMBER,DRIVER_INTER_TOTAL,DUN_BRADSTREET_NO,EMAIL_ADDRESS,FAX,FLEETSIZE,HM_Ind,INTERSTATE_BEYOND_100_MILES,INTERSTATE_WITHIN_100_MILES,INTRASTATE_BEYOND_100_MILES,INTRASTATE_WITHIN_100_MILES,LEGAL_NAME,MAIL_BARRIO,MAIL_NATIONALITY_INDICATOR,MCS150_DATE,MCS150_MILEAGE,MCS150_MILEAGE_YEAR,MCS150_UPDATE_CODE_ID,MCS151_MILEAGE,MCSIPDATE,MCSIPSTEP,OWNBUS_16,OWNCOACH,OWNLIMO_16,OWNLIMO_1_8,OWNLIMO_9_15,OWNSCHOOL_16,OWNSCHOOL_1_8,OWNSCHOOL_9_15,OWNTRACT,OWNTRAIL,OWNTRUCK,OWNVAN_1_8,OWNVAN_9_15,PHONE,PHY_BARRIO,PHY_CITY,PHY_CNTY,PHY_COUNTRY,PHY_NATIONALITY_INDICATOR,PHY_OMC_REGION,PHY_STATE,PHY_STREET,PHY_ZIP,POINTNUM,POWER_UNITS,PRIOR_REVOKE_DOT_NUMBER,PRIOR_REVOKE_FLAG,RECORDABLE_CRASH_RATE,REVIEW_DATE,REVIEW_ID,REVIEW_TYPE,SAFETY_INV_TERR,SAFETY_RATING,SAFETY_RATING_DATE,STATUS_CODE,TOTAL_CARS,TOTAL_CDL,TOTAL_DRIVERS,TOTAL_INTRASTATE_DRIVERS,TRMBUS_16,TRMCOACH,TRMLIMO_16,TRMLIMO_1_8,TRMLIMO_9_15,TRMSCHOOL_16,TRMSCHOOL_1_8,TRMSCHOOL_9_15,TRMTRACT,TRMTRAIL,TRMTRUCK,TRMVAN_1_8,TRMVAN_9_15,TRPBUS_16,TRPCOACH,TRPLIMO_16,TRPLIMO_1_8,TRPLIMO_9_15,TRPSCHOOL_16,TRPSCHOOL_1_8,TRPSCHOOL_9_15,TRPTRACT,TRPTRAIL,TRPTRUCK,TRPVAN_1_8,TRPVAN_9_15,TRUCK_UNITS,UNDELIV_PHY
61121,20120924,NaN,NaN,NaN,0.0,ANDREWS,3,US,TX,1828 NW AVE F,NaN,79714,A,C,NaN,PRIVATE PROPERTY,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2345072,595.0,0.0,fleet@kv-p.com,4325239816,T,N,595.0,0.0,0.0,0.0,KVP ENERGY SERVICES LLC,NaN,NaN,20250224 2146,10669997.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,237.0,466.0,NaN,NaN,4.325232e+09,NaN,ANDREWS,3,US,NaN,NaN,TX,1828 NW AVE F,79714,NaN,538,NaN,NaN,0.000,20160831.0,NaN,C,NaN,S,20160907.0,A,NaN,205.0,595.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,538,NaN
415212,20090109,NaN,NaN,NaN,0.0,HOUSTON,201,US,TX,925 SOUTH LOOP WEST,NaN,77054,A,C,NaN,PRIVATE PROPERTY;AUTHORIZED FOR HIRE,NaN,NaN,NaN,X,X,"CRANES,RIGGING",NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,806882.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,1843980,400.0,130416530.0,ariddick@tntcrane.com,NaN,T,N,400.0,0.0,0.0,0.0,TNT CRANE & RIGGING INC,NaN,NaN,20251006 1346,20000000.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.0,700.0,300.0,NaN,NaN,NaN,NaN,HOUSTON,201,US,NaN,NaN,TX,925 SOUTH LOOP WEST,77054,NaN,500,NaN,NaN,0.000,20110922.0,NaN,C,NaN,S,20130103.0,A,NaN,400.0,400.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500,NaN
277879,19940614,0.0,CORPORATION,3.0,0.0,FORT WORTH,439,US,TX,2201 SCOTT AVENUE,NaN,76103,A,C,4.798713e+09,PRIVATE PROPERTY,RANDALL LYNE,DYLAN MCNEILL,NaN,NaN,X,"PIPES, TANKS, PUMPS",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,PREFERRED PUMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,566051,159.0,71196062.0,hwallace@preferredpump.com,8175319959,T,N,42.0,117.0,31.0,92.0,PREFERRED PUMP & EQUIPMENT LP,NaN,NaN,20250129 1449,14631035.0,2024.0,3.0,NaN,20140207.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,115.0,486.0,NaN,NaN,8.174133e+09,NaN,FORT WORTH,439,US,NaN,6.0,TX,2201 SCOTT AVENUE,76103,P,489,NaN,N,NaN,20131028.0,NaN,C,D,S,20160523.0,A,NaN,128.0,282.0,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,489,NaN
405069,19981007,0.0,CORPORATION,3.0,0.0,HOUSTON,201,US,TX,2050 W SAM HOUSTON PARKWAY S,NaN,77042,A,C,9.197109e+09,PRIVATE PROPERTY;AUTHORIZED FOR HIRE,PATRICK DOVIGI,SAMMY MCKEEL,NaN,NaN,X,RECYCLABLES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GFL ENVIROMENTAL,81830.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,775195,0.0,NaN,smckeel@gflenv.com,NaN,T,N,0.0,NaN,0.0,349.0,WCA WASTE CORPORATION,NaN,NaN,20260506 1047,9578579.0,2025.0,1.0,NaN,20230710.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,48.0,477.0,NaN,NaN,9.843013e+09,NaN,HOUSTON,201,US,NaN,6.0,TX,2050 W SAM HOUSTON PARKWAY S,77042,NaN,486,NaN,N,0.720,NaN,NaN,NaN,H,NaN,NaN,A,NaN,349.0,349.0,349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,486,NaN
562500,20021211,NaN,NaN,NaN,0.0,CYPRESS,201,US,TX,14140 CYPRESS NORTH HOUSTON,NaN,77429,A,C,NaN,PRIVATE PROPERTY,NaN,NaN,NaN,X,X,MATERIALS OF TRADE,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,X,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1079468,76.0,0.0,mike.lambrecht@mpnexlevel.us,3209632416,T,N,56.0,20.0,0.0,400.0,MP TECHNOLOGIES LLC,NaN,NaN,20241022 1543,8000000.0,2023.0,NaN,NaN,20241010.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,335.0,484.0,NaN,NaN,3.209632e+09,NaN,CYPRESS,201,US,NaN,NaN,TX,14140 CYPRESS NORTH HOUSTON,77429,NaN,485,NaN,NaN,NaN,20090107.0,NaN,C,NaN,S,20090108.0,A,NaN,345.0,476.0,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,485,NaN
482336,20100127,NaN,NaN,NaN,0.0,BROWNWOOD,49,US,TX,PO BOX 1166,NaN,76804,A,C,NaN,PRIVATE PROPERTY,NaN,NaN,NaN,NaN,NaN,READY MIX CONCRETE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GOLDEN SPREAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1988441,NaN,0.0,gonzalesrol@vmcmail.com,NaN,T,N,7.0,12.0,18.0,314.0,INGRAM CONCRETE LLC,NaN,NaN,20230424 1844,9376877.0,2021.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0,185.0,319.0,NaN,NaN,NaN,NaN,EULESS,439,US,NaN,NaN,TX,331 NORTH MAIN STREET,76039,NaN,484,NaN,NaN,0.640,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,351.0,351.0,332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,484,NaN
272181,19921027,0.0,CORPORATION,3.0,0.0,NACOGDOCHES,347,US,TX,PO BOX 630610,NaN,75963,A,C,NaN,PRIVATE PROPERTY,WILLIAM ELLIOTT,SHELBI MOONEY,NaN,NaN,X,ELECTRICAL SUPPLIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ELLIOTT ELECTRIC SUPPLY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,502385,465.0,57185928.0,VERTISTHACKER@ELLIOTTELECTRIC.COM,9365858649,T,N,0.0,465.0,0.0,0.0,ELLIOTT ELECTRIC SUPPLY INC,NaN,NaN,20260410 1137,11473423.0,2025.0,3.0,NaN,20180713.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,473.0,NaN,NaN,9.365691e+09,NaN,NACOGDOCHES,347,US,NaN,6.0,TX,2526 NORTH STALLINGS DRIVE,75964,P,479,NaN,N,NaN,NaN,NaN,NaN,D,NaN,NaN,A,NaN,31.0,465.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,479,NaN
29496,20040114,0.0,NaN,NaN,0.0,HOUSTON,201,US,TX,11740 KATY FREEWAY SUITE 1200,NaN,77079,A,C,8.662755e+09,PRIVATE PROPERTY;AUTHORIZED FOR HIRE,DAVE RUSSELL,JENNIFER THOMAS,NaN,NaN,X,PALLETS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,597440.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,1200996,435.0,NaN,andrew.gerrard@48Forty.com,NaN,T,N,435.0,NaN,NaN,NaN,48FORTY SOLUTIONS LLC,NaN,NaN,20260324 1454,25671353.0,2024.0,NaN,NaN,20101211.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,7002.0,12.0,NaN,NaN,8.662755e+09,NaN,HOUSTON,201,US,NaN,NaN,TX,11740 KATY FREEWAY SUITE 1200,77079,P,462,NaN,N,0.133,20101103.0,NaN,C,NaN,S,20101124.0,A,NaN,435.0,435.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431.0,9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,462,NaN
551182,19901015,0.0,CORPORATION,3.0,0.0,DALLAS,113,US,TX,5710 LBJ FREEWAY SUITE 300,NaN,75240,A,C,2.142136e+09,PRIVATE PROPERTY;AUTHORIZED FOR HIRE,RAY MILLS,KEN FERNANDEZ,NaN,NaN,X,"ICE, ICE MACHINES",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REDDY ICE,493748.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,423998,555.0,364514133.0,lMILLS@REDDYICE.COM,2145280686,T,N,40.0,515.0,0.0,0.0,REDDY ICE LLC,NaN,NaN,20250718 1447,9250000.0,2025.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,153.0,29.0,NaN,NaN,2.142136e+09,NaN,DALLAS,113,US,NaN,9.0,TX,5710 LBJ FREEWAY SUITE 300,75240,NaN,461,NaN,N,NaN,20150717.0,NaN,C,G,S,20160126.0,A,NaN,453.0,555.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189.0,273.0,203.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,461,NaN
435735,20110923,0.0,NaN,NaN,0.0,DIMMITT,69,US,TX,PO BOX 1023,NaN,79027,A,C,9.792201e+09,PRIVATE PROPERTY;AUTHORIZED FOR HIRE,EMILIO CHAVEZ,NaN,NaN,NaN,X,AGRICULTURAL COMMODITIES,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,X,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,775867.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,2195271,220.0,NaN,EMILIO@AGRILOGICS.NET,8065531135,T,N,120.0,100.0,80.0,120.0,CROSS INTEGRATED TRANSPORT LLC,NaN,NaN,20260417 1021,41418066.0,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161.0,124.0,NaN,NaN,NaN,8.064781e+09,NaN,DALHART,111,US,NaN,NaN,TX,3263 FM 297,79022,NaN,461,NaN,N,NaN,20241010.0,2175256.0,C,NaN,S,20250731.0,A,NaN,420.0,420.0,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.0,600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,461,NaN
435881,20110928,0.0,NaN,NaN,0.0,LAREDO,479,US,TX,13522 EVOLUTION LOOP,NaN,78045,A,C,9.564892e+09,AUTHORIZED FOR HIRE,OSCAR A. GOMEZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,762399.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,2196912,442.0,NaN,OSCAR.GOMEZ@TEXASIE.COM GOMEZ@TEXASIE.COM,NaN,T,N,442.0,0.0,0.0,0.0,TEXAS INTERNATIONAL ENTERPRISES INC,NaN,NaN,20260316 1319,47186385.0,2025.0,NaN,47186385.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,434.0,1274.0,NaN,NaN,NaN,9.564413e+09,NaN,LAREDO,479,US,NaN,NaN,TX,13522 EVOLUTION LOOP,78045,NaN,448,NaN,N,0.000,20190627.0,NaN,C,NaN,S,20190709.0,A,NaN,442.0,442.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448,NaN
552614,19910221,NaN,CORPORATION,3.0,0.0,SAN JUAN,215,US,TX,P O BOX 87,NaN,78589,A,C,NaN,AUTHORIZED FOR HIRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152490.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,437028,231.0,556529493.0,jdgarza@spirittrucklines.com,NaN,T,N,208.0,0.0,0.0,10.0,SPIRIT TRUCK LINES LLC,NaN,NaN,20240727 1348,30537000.0,2023.0,1.0,NaN,20201007.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SAN JUAN,215,US,NaN,6.0,TX,200 WEST NOLANA,78589,NaN,446,NaN,NaN,NaN,20080718.0,NaN,C,S,S,20081001.0,A,NaN,218.0,218.0,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223.0,957.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223,NaN
472365,19820707,0.0,CORPORATION,3.0,0.0,DALLAS,113,US,TX,PO BOX 650205,NaN,75265-0205,A,C,2.149124e+09,PRIVATE PROPERTY,KEVIN AKERS,DAN MEZIERE,NaN,NaN,X,NATURAL GAS UTILITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216478,8.0,178915146.0,Brian.perez@atmosEnergy.com,9728553085,T,Y,NaN,8.0,13.0,824.0,ATMOS ENERGY CORPORATION,NaN,NaN,20251017 1241,2234742.0,2024.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,161.0,81.0,NaN,NaN,9.728553e+09,NaN,DALLAS,113,US,NaN,4.0,TX,5430 LYNDON B JOHNSON FREEWAY 1800,75240,NaN,441,NaN,N,NaN,NaN,NaN,NaN,N,NaN,NaN,A,NaN,845.0,845.0,837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,265.0,344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,440,NaN
77841,20160323,0.0,NaN,NaN,0.0,DALLAS,113,US,TX,14185 DALLAS PKWY STE 300,NaN,75254,A,C,NaN,OTHER-INTRASTATE;AUTHORIZED FOR HIRE,HESSEL VERHAGE,TRENT HOBAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CCRF,962129.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,2869944,307.0,NaN,CARRIE.DEPEW@COPART.COM,NaN,T,N,307.0,0.0,0.0,0.0,COPART CATASTROPHE RESPONSE FLEET LLC,NaN,NaN,20250918 1645,25135854.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.0,435.0,NaN,NaN,2.144326e+09,NaN,DALLAS,113,US,NaN,NaN,TX,14185 DALLAS PKWY STE 300,75254,NaN,435,NaN,N,88.550,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,184.0,307.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,435,NaN
252960,20060809,0.0,NaN,NaN,0.0,TYLER,423,US,TX,1820 S SW LOOP 323,NaN,75701,A,C,9.034956e+09,PRIVATE PROPERTY,BRANDI HARLAN,NaN,NaN,NaN,X,COMM. HARDWARE,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OPTIMUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1540537,440.0,NaN,brandi.harlan@alticeusa.com,NaN,T,N,NaN,440.0,NaN,NaN,CEBRIDGE ACQUISITION LP,NaN,NaN,20251008 1932,6083805.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432.0,NaN,NaN,9.034956e+09,NaN,TYLER,423,US,NaN,NaN,TX,1820 S SW LOOP 323,75701,NaN,432,NaN,N,0.000,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,3.0,440.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432,NaN
502327,20020419,0.0,NaN,NaN,0.0,NEW BRAUNFELS,91,US,TX,4772 FM 482,NaN,78132,A,C,NaN,AUTHORIZED FOR HIRE,RYAN WYATT,NaN,NaN,NaN,X,GRAVEL/SAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AGGREGATE HAULERS,429708.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,1021485,59.0,NaN,POLIVAREZ@AHLP.COM,NaN,T,N,59.0,0.0,62.0,308.0,AGGREGATE HAULERS I L P,NaN,NaN,20251216 1019,15412000.0,2024.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.104926e+09,NaN,NEW BRAUNFELS,91,US,NaN,6.0,TX,4772 FM 482,78132,NaN,429,NaN,N,NaN,20230525.0,NaN,C,S,S,20230531.0,A,NaN,429.0,429.0,370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,429.0,429.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,429,NaN
80587,20160520,0.0,NaN,NaN,0.0,DALLAS,113,US,TX,14911 QUORUM DR STE 200,NaN,75254-7003,A,C,3.252127e+09,PRIVATE PROPERTY,CODY RENFRO,MATT SWILLING,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GLAZER'S BEER AND BEVERAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2892687,40.0,80227202.0,cody.renfro@glazersbeer.com,NaN,T,N,20.0,20.0,160.0,150.0,GLAZER'S BEER AND BEVERAGE LLC,NaN,NaN,20260521 1200,7500000.0,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,372.0,361.0,56.0,NaN,NaN,9.723928e+09,NaN,DALLAS,113,US,NaN,NaN,TX,14911 QUORUM DR SUITE 200,75254,NaN,428,NaN,N,1.440,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,275.0,350.0,310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,428,NaN
471493,19740601,NaN,CORPORATION,3.0,0.0,DALLAS,113,US,TX,8585 N STEMMONS FWY STE 600S,NaN,75247,A,C,9.405779e+09,PRIVATE PROPERTY,MICHAEL HARRIS,ALAYNA FINMAN,NaN,NaN,X,BATTERIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194390,140.0,49046410.0,afinman@gocbs.com,8176186117,T,N,80.0,60.0,95.0,204.0,CONTINENTAL BATTERY COMPANY,NaN,NaN,20260416 0000,14426000.0,2025.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,9.0,403.0,NaN,NaN,4.694581e+09,NaN,DALLAS,113,US,NaN,6.0,TX,8585 N STEMMONS FWY STE 600S,75247,NaN,419,NaN,N,NaN,20071108.0,NaN,C,D,S,20071112.0,A,361.0,138.0,439.0,299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,419,NaN
265851,20140403,0.0,NaN,NaN,0.0,HOUSTON,201,US,TX,8723 FALLBRROK DR,NaN,77064,A,C,8.327230e+09,PRIVATE PROPERTY,ALAN JOHANSEN,TOBIAS JONES,NaN,NaN,X,ELECTRICAL EQUIPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESA SERVICE AND RESA HIGH VOLTAGE SERVICE AND...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2491903,300.0,NaN,VALER.BANUSHI@RESAPOWER.COM,NaN,T,N,300.0,0.0,0.0,0.0,RESA POWER SERVICE LLC,NaN,NaN,20260311 1127,650000.0,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,24.0,45.0,NaN,NaN,9.799970e+09,NaN,HOUSTON,201,US,NaN,NaN,TX,8723 FALLBROOK DR,77064,NaN,404,NaN,N,0.000,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,22.0,300.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,404,NaN
63271,20140926,NaN,NaN,NaN,0.0,CARROLLTON,113,US,TX,1325 W BELT LINE RD,NaN,75006,A,C,NaN,AUTHORIZED FOR HIRE,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN,284464.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,2545275,351.0,0.0,verify@vsstg.com,NaN,S,N,325.0,26.0,0.0,0.0,VSS TRANSPORTATION GROUP INC,NaN,NaN,20260513 1302,41108654.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239.0,700.0,1.0,NaN,NaN,NaN,NaN,CARROLLTON,113,US,NaN,NaN,TX,1325 W BELT LINE RD,75006,NaN,400,NaN,NaN,0.000,20170821.0,NaN,C,NaN,S,20170821.0,A,NaN,351.0,351.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,NaN
259593,20130920,NaN,NaN,NaN,0.0,GAINESVILLE,97,US,TX,PO BOX 340,NaN,76241,A,C,NaN,PRIVATE PROPERTY;AUTHORIZED FOR HIRE,NaN,NaN,NaN,NaN,X,"NON POTABLE WATER, POTABLE WATER, SEPTIC WASTE",NaN,NaN,NaN,X,X,NaN,NaN,X,NaN,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,841540.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,2439611,223.0,0.0,jpittmon@rentpeak.com,NaN,S,Y,200.0,23.0,0.0,14.0,PEAK RENTALS LLC,NaN,NaN,20250124 2011,3127148.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,1789.0,67.0,NaN,NaN,9.402846e+09,NaN,GAINESVILLE,97,US,NaN,NaN,TX,3333 N I-35 STE 200,76240,NaN,390,NaN,NaN,1.330,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,79.0,237.0,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,1.0,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390,NaN
300874,20110518,NaN,NaN,NaN,0.0,LAREDO,479,US,TX,12115 DOC ADAMS,NaN,78045,A,C,9.566082e+09,AUTHORIZED FOR HIRE,ROBERT GUME GARZA,AMY RAMOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,749123.0,MC,A,NaN,NaN,NaN,NaN,NaN,NaN,2154826,317.0,NaN,ARAMOS@FREIGHTSOL.NET,9565130484,S,N,316.0,1.0,NaN,NaN,FREIGHTSOL LLC,NaN,NaN,20251205 0000,30000000.0,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,322.0,261.0,NaN,NaN,NaN,9.564138e+09,NaN,LAREDO,479,US,NaN,NaN,TX,12115 DOC ADAMS,78045,NaN,381,NaN,N,0.000,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,317.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,510.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381,NaN

In [12]:
filt_df['Match'] = (filt_df['POWER_UNITS'] == filt_df['TRUCK_UNITS']) # Check wether column values 'filt_df['POWER_UNITS']' and 'filt_df['TRUCK_UNITS']' 
pd.set_option('display.max_rows', None)
filt_df['Match'] # displays a boolean values in each row regarding if our previos Series obj data match

61121      True
415212     True
277879     True
405069     True
562500     True
482336     True
272181     True
29496      True
551182     True
435735     True
435881     True
552614    False
472365    False
77841      True
252960     True
502327     True
80587      True
471493     True
265851     True
63271      True
259593     True
300874     True
498871     True
355461     True
360475     True
470642     True
221764    False
248339    False
79227      True
221871    False
502238     True
408757     True
298669     True
264061    False
39959      True
551820     True
414126     True
357698     True
484572     True
417888     True
273485     True
27637     False
260084     True
478834     True
4505       True
223985    False
438845     True
61540      True
70050      True
367637     True
474024     True
279586     True
432        True
226514    False
224486    False
492845     True
553826    False
347938     True
472198     True
65010      True
402664     True
34689      True
31135      True
306823     True
294780    False
604006     True
360048     True
48346      True
16482      True
396964     True
397144     True
373671     True
53798     False
9846      False
496756     True
464705    False
489546     True
53356      True
296544     True
188927     True
357499     True
92352      True
53392     False
55253      True
499975     True
557046     True
417860     True
44795      True
488175     True
58372      True
221921     True
17878      True
475475     True
367649    False
6176      False
248836     True
145648     True
22453      True
1394       True
58545      True
243853     True
482189     True
53004     False
475391     True
396969     True
472836     True
330202     True
283169    False
549848     True
65510      True
564757     True
362319     True
395700     True
19841      True
92717      True
122600     True
607779     True
326445    False
312534     True
59510      True
391455    False
476337     True
480037     True
140507     True
478073     True
414692     True
38112      True
128689     True
1860       True
393721     True
3317      False
479169     True
358888    False
358521     True
481393     True
502066     True
51976      True
437518     True
3517       True
224116    False
270732     True
124078     True
563247     True
548816     True
84051      True
413073     True
83948      True
229259     True
488861     True
359297    False
78905      True
300273     True
467779     True
24600      True
300403    False
35065      True
229468     True
367936     True
391241     True
102420     True
287634     True
252981     True
300686    False
244067    False
64826      True
485496     True
77704      True
270702     True
263787     True
307221     True
224025    False
250655    False
560770     True
489342     True
241433     True
418207     True
8669       True
257107     True
449054     True
3685      False
399840     True
568613     True
43670      True
551637     True
356325     True
276884     True
28070      True
410483     True
367523     True
359012     True
33303      True
55266      True
460940     True
24374      True
393353     True
486155     True
381471    False
560545     True
484615     True
8596       True
405358     True
377849     True
387166    False
35489      True
167194     True
90117      True
389673     True
130850     True
463316     True
129659     True
397726     True
357030    False
36179      True
228426     True
560531     True
44609      True
473209     True
467770    False
478485     True
275946     True
15746      True
428756     True
220668    False
562876     True
328646     True
480877     True
26647      True
437360     True
606541     True
250762     True
243463     True
225795    False
22799      True
266017     True
469774     True
291195    False
394920     True
594113     True
270851    False
94873      True
357032     True
82511      True
296313     True
607638     True
45572      True
360103     True
376222     True
379819     True
553284     True
64841      True
56994      True
298458     True
70913      True
506341     True
382217     True
292515     True
345321    False
22593     False
472246     True
315718     True
286345     True
564900     True
473641     True
293172     True
312360     True
497261     True
135650     True
498149     True
3329       True
392147     True
344598     True
548436     True
386523     True
70859      True
332487     True
117375    False
259084     True
435320     True
63122      True
472228     True
59364      True
298018     True
45934      True
4292       True
37099      True
391802     True
231267     True
255764     True
397393     True
368234     True
256727     True
219272    False
4595      False
455572     True
343712     True
254735    False
24326      True
261614     True
46894      True
377578     True
2027       True
397446     True
15298      True
88627      True
485301    False
134187     True
564297     True
471242     True
260374     True
257696     True
499433     True
12112      True
491287     True
31054      True
45943      True
119533     True
421608     True
6683      False
11249      True
109851     True
551568     True
69652      True
25145      True
476878     True
18572      True
373049     True
107285     True
360541     True
265437     True
472568     True
324077     True
11411      True
226993     True
551194     True
33367      True
106294     True
407605    False
603751     True
557397    False
355939     True
305586     True
113016     True
222012    False
438019     True
240354     True
260205     True
278649     True
97732      True
108227     True
7339       True
451115     True
411860     True
478482     True
477771     True
368321     True
402835     True
119153     True
299793     True
474661     True
4590       True
382381     True
548986     True
475413     True
230085     True
524907     True
388075     True
51890      True
49034     False
233207     True
464994    False
42719     False
413035     True
310951     True
436624     True
271636     True
298567     True
37020      True
507395     True
500007     True
367383     True
253812     True
274401     True
232785     True
249916     True
1691       True
144839     True
356102     True
413760     True
245061     True
358757     True
107750     True
74944      True
241078     True
409750     True
221775    False
171222     True
2630       True
46357      True
524280    False
388443     True
410802    False
63178      True
101360     True
332765     True
14309      True
605572    False
385457     True
77052      True
68731      True
449529     True
473281     True
289069     True
359575     True
443794     True
408484     True
370394     True
379756     True
243477     True
491420    False
551697     True
438025     True
50172      True
247287     True
247620     True
583946     True
80062      True
394284     True
493522     True
360330     True
484213     True
482275     True
158020     True
441723     True
255761     True
487723    False
23698      True
392737     True
550416     True
21498     False
397120     True
84467     False
39059     False
232194     True
473198     True
473411     True
61144     False
425964     True
126797    False
368973     True
362759     True
112680     True
474676     True
481045     True
263847     True
238422     True
248832     True
242880     True
3621       True
247069    False
73569     False
301656     True
122463     True
56577      True
53863      True
74         True
296904     True
25340      True
26608      True
472340     True
494571     True
191730     True
590849     True
62752      True
502247     True
82890      True
50457      True
108444     True
474195     True
25341      True
358934     True
483044     True
331406     True
550419     True
360054     True
555544     True
561789     True
479786    False
125898     True
63055      True
841        True
588730     True
303924    False
416737     True
357037     True
362581     True
298385     True
308810     True
550887     True
19442      True
7536       True
87066      True
478986     True
290111     True
63066      True
62108      True
565570     True
51370      True
286383     True
501554     True
56344      True
557670     True
402746     True
112220     True
6718      False
370760     True
364199    False
313351     True
64194      True
10161      True
362779     True
392187     True
407948     True
46950      True
67301      True
553480     True
20865     False
14327      True
109393     True
174737     True
478084     True
315114     True
300125     True
512543     True
423942     True
388027     True
553902     True
225217    False
85346      True
508159     True
295143     True
355394     True
368851     True
34592      True
493044     True
22402      True
37969      True
39060     False
389632    False
361598     True
303001     True
331388     True
68992      True
32238      True
608667     True
248150     True
255064     True
68742      True
37511      True
438068     True
442344    False
403223     True
359007    False
580267     True
357013     True
300475     True
312885     True
324531     True
106897    False
552874     True
257273     True
106698     True
35760      True
480042     True
473869     True
148462     True
405141     True
432029     True
605590     True
436483     True
126650     True
87761      True
12875      True
259363    False
42114      True
544005     True
542962     True
9966       True
78846      True
64573      True
412522     True
398743     True
478723     True
59365      True
269173     True
277294    False
254178     True
228875     True
469726     True
277454     True
171287     True
36821      True
1546       True
587890     True
331836     True
298420     True
170945     True
154753     True
488525     True
83684      True
22626      True
604445     True
6583       True
77173      True
50004      True
64810      True
44646      True
32978      True
472605     True
114716     True
175384     True
296248     True
408038     True
311495     True
296760    False
309695     True
466602     True
305685     True
393797     True
370032     True
357823     True
414747     True
246695     True
237550     True
65319      True
513846     True
489252     True
231823     True
262567     True
406787    False
47564      True
79517      True
392893     True
300652     True
435669     True
165866     True
608861     True
24197      True
375121     True
399806     True
246722     True
264884     True
608275     True
485468     True
79859      True
54931      True
29648      True
334595     True
330910     True
411964     True
466237     True
383233     True
385462     True
400476     True
478448     True
257495    False
449890     True
450713     True
374390     True
362070     True
330600    False
433807     True
604842     True
269254     True
224245    False
81153      True
110591     True
96206      True
479767     True
87745      True
9209       True
35193     False
370224    False
418900     True
246076     True
233577     True
232089     True
474956     True
84891      True
486807     True
117060     True
274607     True
62214      True
72876      True
498184     True
31085      True
Name: Match, dtype: bool

In [13]:
# Count the number of unmatching data (False values) for our 'Match' column (filt_df['Match'])
count = 0
for i in filt_df['Match']:
    if (i == False):
        count += 1
print(count)

# Out of 695 values, there are 87 rows data regarding 'POWER_UNITS' and 'TRUCK_UNITS' columns that do not match, approx a 12% of our total (0.124 * 695 = 86.18)
# 'Losing more than 2% to 5% of your dataset without investigation can introduce severe bias into your final analysis'.
# Then, the idea of merging columns is discarded, and rather keep working with only with the 'POWER_UNIT' Series obj

87

In [14]:
# Visualize filtered data regarding useful columns
filt_df[['LEGAL_NAME', 'PHY_STATE', 'PHY_STREET', 'PHY_ZIP', 'POWER_UNITS']]

,LEGAL_NAME,PHY_STATE,PHY_STREET,PHY_ZIP,POWER_UNITS
61121,KVP ENERGY SERVICES LLC,TX,1828 NW AVE F,79714,538
415212,TNT CRANE & RIGGING INC,TX,925 SOUTH LOOP WEST,77054,500
277879,PREFERRED PUMP & EQUIPMENT LP,TX,2201 SCOTT AVENUE,76103,489
405069,WCA WASTE CORPORATION,TX,2050 W SAM HOUSTON PARKWAY S,77042,486
562500,MP TECHNOLOGIES LLC,TX,14140 CYPRESS NORTH HOUSTON,77429,485
482336,INGRAM CONCRETE LLC,TX,331 NORTH MAIN STREET,76039,484
272181,ELLIOTT ELECTRIC SUPPLY INC,TX,2526 NORTH STALLINGS DRIVE,75964,479
29496,48FORTY SOLUTIONS LLC,TX,11740 KATY FREEWAY SUITE 1200,77079,462
551182,REDDY ICE LLC,TX,5710 LBJ FREEWAY SUITE 300,75240,461
435735,CROSS INTEGRATED TRANSPORT LLC,TX,3263 FM 297,79022,461
435881,TEXAS INTERNATIONAL ENTERPRISES INC,TX,13522 EVOLUTION LOOP,78045,448
552614,SPIRIT TRUCK LINES LLC,TX,200 WEST NOLANA,78589,446
472365,ATMOS ENERGY CORPORATION,TX,5430 LYNDON B JOHNSON FREEWAY 1800,75240,441
77841,COPART CATASTROPHE RESPONSE FLEET LLC,TX,14185 DALLAS PKWY STE 300,75254,435
252960,CEBRIDGE ACQUISITION LP,TX,1820 S SW LOOP 323,75701,432
502327,AGGREGATE HAULERS I L P,TX,4772 FM 482,78132,429
80587,GLAZER'S BEER AND BEVERAGE LLC,TX,14911 QUORUM DR SUITE 200,75254,428
471493,CONTINENTAL BATTERY COMPANY,TX,8585 N STEMMONS FWY STE 600S,75247,419
265851,RESA POWER SERVICE LLC,TX,8723 FALLBROOK DR,77064,404
63271,VSS TRANSPORTATION GROUP INC,TX,1325 W BELT LINE RD,75006,400
259593,PEAK RENTALS LLC,TX,3333 N I-35 STE 200,76240,390
300874,FREIGHTSOL LLC,TX,12115 DOC ADAMS,78045,381
498871,GOODMAN DISTRIBUTION INC,TX,19001 KERMIER RD,77484,377
355461,OLDCASTLE BUILDINGENVELOPE INC,TX,5430 LBJ FWY STE 900,75240,369
360475,SYSCO USA II LLC,TX,1390 ENCLAVE PARKWAY,77077,366
470642,SOUTHERN MAIL SERVICE INC,TX,2505 N FRAZIER,77303,361
221764,YELLOWJACKET OILFIELD SERVICES,TX,620 FOUR S INDUSTRIAL BLVD,75662-5292,357
248339,YJOS LLC,TX,620 FOUR S INDUSTRIAL BLVD,75662-5292,357
79227,SPG TRANSPORTATION INC,TX,1102 AVENUE R,75050,357
221871,"RAIDER EXPRESS, INC",TX,12544 NW HWY 287,76052,355
502238,WARREN POWER & MACHINERY INC,TX,15 SMITH RD,79705,353
408757,RAIDER EXPRESS INC,TX,12544 NW HWY 287,76052,350
298669,JUST IN TIME CARGO INC,TX,15825 W TRINITY BLVD,76155,348
264061,ANGULO TRANSPORTATION SERVICE LLC,TX,216 PINTO VALLE,78045,346
39959,ENTERGY TEXAS INC,TX,60 N 11TH ST,77703,345
551820,KINDER MORGAN INC,TX,1001 LOUISIANA STE 1000,77002,341
414126,TITUS TRANSPORT HOLDINGS LLC,TX,2800 SHORELINE DRIVE,76210,335
357698,HULCHER SERVICES INC,TX,611 KIMBERLY DR STE 101,76208-6385,332
484572,XLR8 DELIVERY INC,TX,1310 E RICHEY RD,77073,331
417888,SELECT DEDICATED SOLUTIONS LLC,TX,12375 MINES RD,78045,329
273485,RUSSELL TRANSPORT INC,TX,12365 PINE SPRINGS,79928,329
27637,KIMRAD TRANSPORT LP,TX,371 WEST LOOP 335 SOUTH,79118,322
260084,MULHOLLAND ENERGY SERVICES LLC,TX,10308 WCR 72,79707,316
478834,GFL PLANT SERVICES LP,TX,16011 W BELLFORT ST,77498,312
4505,CHALK MOUNTAIN SERVICES OF TEXAS LLC,TX,1701 RIVER RUN SUITE 200,76107,308
223985,STV INCORPORATED,TX,5750 GENESIS CT,75034-4163,305
438845,DVP TRUCKING LLC,TX,12501 TECH RIDGE BLVD APT 1228,78753,300
61540,M&J CARRIERS LLC,TX,14218 BUSINESS AVE,78045,292
70050,TEXAS FIRST RENTALS LLC,TX,5665 SE LOOP 410,78222,287
367637,TIMCO LOGISTICS SYSTEMS LLC,TX,2270 W US HWY 287 BUSINESS,75167,285
474024,VERIZON BUSINESS,TX,700 HIDDEN RIDGE MC HQW0BH50,75038,283
279586,NATIONAL TRENCH SAFETY INC,TX,260 N SAM HOUSTON PKWY E STE 200,77060,282
432,CUSTOM COMMODITIES INC,TX,408 TRINITY ST,75644,275
226514,ENERGY SOLUTIONS (US) LLC,TX,2465 TECHNOLOGY FOREST BLVD,77381,270
224486,"FRONTIER TANK LINES, INC.",TX,6850 TPC DR,75070-3145,268
492845,RK SUPPLY,TX,11400 W CNTY RD 30,79707,266
553826,STREAMTECH INC,TX,4550 POST OAK PLACE DRIVE STE #335,77027,265
347938,1884 LINE CO,TX,3831 TECHNOLOGY FOREST BLVD,77381,264
472198,PARKWAY TRANSPORT INC,TX,5711 FM 78,78244,261
65010,BDG TREES LLC,TX,2015 AHRENS ST,77017,257
402664,FLYING A PUMPING SERVICES LLC,TX,14902 I 20 N SERVICE ROAD,76437,252
34689,SOUTHERN TRANSPORT LLC,TX,24291 FM 1252,75647,250
31135,HYDRO RESOURCES MID CONTINENT INC,TX,7531 FM 119,79086,249
306823,AXIS POWER LLC,TX,4B BAYOUBRANDT,77706,245
294780,NATIONAL HME INC,TX,7651 ESTERS BLVD SUITE 125,75063,245
604006,EXPEDITED LOGISTICS AND FREIGHT SERVICES LLC,TX,3031 EASTVELD DR,77073,244
360048,PALLETIZED TRUCKING INC,TX,2001 COLLINGSWORTH,77009,243
48346,TRANCASA USA INC,TX,100 S AUSTIN DR,78577-9796,243
16482,PINNERGY LTD,TX,2801 VIA FORTUNA SUITE 440,78746,241
396964,SILVERTIP COMPLETION SERVICES OPERATING LLC,TX,9816 W COUNTY ROAD 146,79706,240
397144,MAX CARGO LLC,TX,6012 N COUNTY RD 1147,79705,240
373671,D-TROY LOGISTICS LLC,TX,5700 TENNYSON PARKWAY SUITE 300,75024,240
53798,RED ZONE COIL TUBING LLC,TX,3308 STATE HWY 135N,75662,239
9846,A L HELMCAMP INCORPORATED,TX,4120 HWY 79 WEST,75831,239
496756,ROYAL FREIGHT LP,TX,407 WEST SIOUX ROAD,78577,238
464705,TERRIER TRANSPORTATION INC,TX,4708 FIDELITY ST,77029,237
489546,FENIX PARTS LLC,TX,860 AIRPORT FWY #701,76054,236
53356,CREST PUMPING TECHNOLOGIES LLC,TX,6500 WEST FRWY SUITE 601,76116,233
296544,PRIMARY UTILITY SERVICES LLC,TX,1505 ROGERS ST,79549,231
188927,FORGED FIBER 37 SERVICES LLC,TX,208 S AKARD ST,75202,231
357499,FREEMAN EXPOSITIONS LLC,TX,14221 NORTH DALLAS PKWY #200,75254,230
92352,FJ CARRIER LOGISTICS LLC,TX,13911 COPPER DR,78045,230
53392,LARRETT ENERGY SERVICES INC,TX,2700 CHAMBERS STREET,76084,226
55253,BRIGHT STAR SOLUTIONS LLC,TX,18788 HWY 105,77659,223
499975,CANO & SONS TRUCKING LLC,TX,109 WEST DICKER RD,78589,222
557046,TANKNOLOGY INC,TX,11000 N MOPAC EXPY SUITE 500,78759,221
417860,JAX TRANSPORT LLC,TX,7600 S FM 1541,79118,221
44795,LIGHTNING OILFIELD SERVICES INC,TX,11830 NORTH SAGINAW BLVD,76179,219
488175,TRI -STATE VACUUM AND RENTAL LLC,TX,12267 US HWY 84 E,75954,217
58372,BROTHERS PRODUCE OF DALLAS INC,TX,2600 MCCREE RD,75041-3901,215
221921,CANO AND SONS TRUCKING LLC,TX,109 W DICKER RD,78589-4796,214
17878,VERIZON WIRELESS INC,TX,700 HIDDEN RIDGE MC HQW0BH50,75038,213
475475,PATE TRUCKING COMPANY LLC,TX,4025 112TH STREET,79423,212
367649,RK HALL LLC,TX,5020 SE LOOP 286,75460,211
6176,UNIQUE LEASING INC,TX,8755 US HWY 87 E,78263,208
248836,FEVID TRANSPORT LLC,TX,300 THROCKMORTON STE 300,76102,205
145648,CRAWFORD ELECTRIC SUPPLY - SONEPAR USA,TX,7701 W LITTLE YORK RD STE 800,77040-5493,204
22453,SKY TRANSPORTATION SERVICES LLC,TX,11650 GATEWAY BLVD E,79927-7702,204
1394,GRACO FISHING & RENTAL TOOLS INC,TX,5300 TOWN AND COUNRY BLVD,75034,204
58545,HUNTER EXPRESS US INC,TX,13151 SOUTH UNITEC DRIVE,78045,202
243853,TRADEX LOGISTICS INC,TX,607 GRAND CENTRAL,78045,201
482189,AMERICANSTAR TRANSPORT LLC,TX,5755 RUFE SNOW DR SUITE 190,76182,201
53004,OAK TRUCK LINES LLC,TX,18658 MINES ROAD,78045,200
475391,CANAL TRANSPORTATION LLC,TX,11643A WALLISVILLE ROAD,77013,199
396969,CRANEWORKS RENTALS LLC,TX,7795 EAST LITTLE YORK RD,77016,198
472836,GULFMARK ENERGY INC,TX,2727 ALLEN PARKWAY STE 900,77019,198
330202,DETMAR TRANSPORT LLC,TX,18615 TUSCANY STONE STE 200,78258,196
283169,FOUNDATION ENERGY SERVICES LLC,TX,3204 W HIGHWAY 180,79549,196
549848,DISTRIBUTOR OPERATIONS INC,TX,14221 DALLAS PARKWAY STE 1000,75254,196
65510,RED STAG LLC,TX,13446 CLEBURNE HIGHWAY,76035,195
564757,QUEST EVENTS LLC,TX,2591 DALLAS PARKWAY STE 201,75034,194
362319,STEP ENERGY SERVICES USA LTD,TX,70 NE LOOP 410 SUITE 600,78216,193
395700,RESOURCE ENVIRONMENTAL SOLUTIONS LLC,TX,6575 W LOOP S STE 300,77401,191
19841,BRIGGS INDUSTRIAL SOLUTIONS,TX,10540 N STEMMONS FRWY,75220,189
92717,RJ TRANSPORTATION SERVICES LLC,TX,8208 CAMINO COLUMBIA TOLL RD N,78045-6835,187
122600,XBL INDUSTRIAL MATERIALS LLC,TX,2901 GREENLEE PARK TRAIL,76088,187
607779,TAS ENVIRONMENTAL SERVICES LP,TX,7301 N STATE HWY 161 STE 450,75039,187
326445,3T CARRIER LLC,TX,16464 US-83,78045,186
312534,APPLE MOVING LLC,TX,5206 WIND RIVER ROAD,78759,185
59510,VAC ONE LEASING LLC,TX,2909 AARON STREET,77536,185
391455,CALDERON TRUCKING INC,TX,203 LOBO LOOP,78045-8480,183
476337,LTS MANAGED TECHNICAL SERVICES LLC,TX,14400 THE LAKES BLVD STE 100 BLDG C,78660,181
480037,RWLS LLC,TX,1937 WEST AVENUE,79336,181
140507,CRANETECH INC,TX,1209 STURGEON CT SUITE 107,76001,180
478073,VTS TRANSPORTATION INC,TX,6100 BANDERA ROAD SUITE 115,78238,180
414692,GULF STATES TRUCKING INC,TX,17131 EAST FWY,77530,180
38112,VORTEX SERVICES LLC,TX,18150 IMPERIAL VALLEY DR,77060,180
128689,KOONER TRUCK REPAIR INC,TX,11027 NORTHPOINT BLVD STE E,77375,179
1860,SUNBURST TRUCK LINES INC,TX,5121 A OATES ROAD,77013,178
393721,TRIPLE RRR CARRIERS INC,TX,20951 MINES ROAD,78045,177
3317,EL PASO ELECTRIC,TX,100 N STANTON,79901,177
479169,ACTION GYPSUM SUPPLY LP,TX,9635 WEST LITTLE YORK RD,77040,177
358888,ENBRIDGE ENERGY LIMITED PARTNERSHIP,TX,915 N ELDRIDGE PKWY SUITE 1100,77079,176
358521,EXPANSE ELECTRICAL COMPANY LLC,TX,1155 DAIRY ASHFORD STE 620,77079,176
481393,JAMES POWER LINE CONSTRUCTION LLC,TX,43 SHOOTING CLUB RD,78006,174
502066,DC TRANSPORTATION SERVICES INC,TX,2620 MCIVEY STREET SUITE B,76111,172
51976,WESTERN CONCRETE PUMPING INC,TX,411 RANKIN CIRCLE N,77073,172
437518,TM TRANSPORTATION SERVICES LLC,TX,13491 SOUTH UNITEC DRIVE,78045,171
3517,CUMMINS SOUTHERN PLAINS LLC,TX,600 N WATSON RD,76011-5319,171
224116,BWI COMPANIES INC.,TX,1355 N KINGS HWY,75569-2121,170
270732,ABSOLUTE GROUP INC,TX,1208 VIDAL CANTU RD,78045,170
124078,KOT SIDHU TRANSPORT INC,TX,2320 E UNION BOWER RD,75061,170
563247,FUTURE INFRASTRUCTURE LLC,TX,3325 INNOVATIVE WAY,75149,166
548816,WEATHERFORD ARTIFICIAL LIFT SYSTEMS LLC,TX,7500 BENBROOK PARKWAY,76126,166
84051,AMG TECHNOLOGY INVESTMENT GROUP LLC,TX,95 PARKER OAKS LN,76087-1265,165
413073,PLASKA TRANSMISSIONN LINE CONSTRUCTION LLC,TX,8901 EAST FM 1151,79118,164
83948,HAIRPIN TRUCKING LLC,TX,1086 SHADY LN,75650,163
229259,GLADIATOR ENERGY LLC,TX,1400 WOODLOCH FOREST DR STE 425,77380,162
488861,ALEMAN TRUCKING LLC,TX,1330 N TOWER RD,78516,162
359297,TARGA TRANSPORT LLC,TX,811 LOUISIANA SUITE 2100,77002-1400,161
78905,FORCE LOGISTICS US LLC,TX,22828 PARK RD,77377,161
300273,BYRD OILFIELD SERVICES LLC,TX,4725 LOOP 322,79602,160
467779,ASPHALT TRANSPORT INC,TX,17311 MARKET STREET,77530,159
24600,TRANSMAQUILA INC,TX,5771 SOUTH PADRE ISLAND HWY,78521,159
300403,FREIGHT SOLUTIONS LLC,TX,15821 KIMBERLEE STREET,77049,159
35065,JETCO DELIVERY LLC,TX,3010 ALDINE BENDER RD,77032,159
229468,COVENANT TRUCKING LLC,TX,3911 SOUTH COUNTY ROAD 1232,79706,159
367936,LINCOLN FREIGHT COMPANY LLC,TX,8417 AMPARAN RD,78045,158
391241,WARRIOR TECHNOLOGIES LLC,TX,400 W ILLINOIS AVE STE 950,79701,157
102420,GENESIS INTERMODAL SERVICES LLC,TX,2714 N LOOP 1604 E STE 202,78232,157
287634,FORGELINE LOGISTICS LLC,TX,2702 SYLVAN WAY,75072,155
252981,FROST FREIGHT INC,TX,6909 SPRINGFIELD AVE STE 106,78045,155
300686,HILCORP ENERGY COMPANY,TX,1111 TRAVIS ST,77002-5924,155
244067,AEGIS CHEMICAL SOLUTIONS LLC,TX,4560 KENDRICK PLAZA DR SUITE 190,77032,154
64826,ROLESA TRANSPORT LLC,TX,6197 E HWY 83,78582,153
485496,GCC SUN CITY MATERIALS LLC,TX,1 MCKELLIGON CANYON RD,79930-2634,153
77704,JMR SERVICES LLC,TX,4706 GREEN TREE BLVD,79707,152
270702,COWBOY'S READY MIX LLC,TX,24015 INTERSTATE 10,77597,150
263787,ALL TIME LOGISTICS INC,TX,4700 IRVING BLVD STE 200A,75247,150
307221,ABURO TRANSPORTATION LLC,TX,835 E LAMAR BLVD PMB207,76011,150
224025,PATTERSON PROFESSIONAL SERVICES,TX,9963 US HIGHWAY 377,76233-2794,148
250655,WS ENERGY SERVICES LLC,TX,709 EAST MAIN AVENUE,78380,148
560770,PATTERSON MOTOR FREIGHT LLC,TX,24955 INTERSTATE 45 NORTH STE 300,77380,148
489342,ARALO EXPRESS USA INC,TX,1902 W CALTON RD,78041,147
241433,WHITE LINE SYSTEMS LLC,TX,19200 MARKETPLACE AVENUE SUITE 102,78640,147
418207,ROCKIN S TRUCKIN INC,TX,5751 WHITE SETTLEMENT RD,76087,146
8669,SCHST LLC,TX,12214 AQUEDUCT RD,77044-5212,146
257107,BALKAN EXPRESS LLC,TX,2560 E LONG AVENUE,76137,145
449054,PDSD SHIPPING LLC,TX,15429 FLUD RD,75143,145
3685,MARITIME SERVICES LTD,TX,8200 TELEPHONE RD,77061-4039,144
399840,SOUTHERN LIFTING AND HOISTING LLC,TX,2409 STATE HWY 135 N,75662,144
568613,USA PLAN LLC,TX,1732 LAKOTA LN,78628,144
43670,TEXSTAR ENTERPRISES LLC,TX,17090 JORDAN ROAD,78154,144
551637,U-HAUL CO OF TEXAS,TX,920 SOUTH MACARTHUR BLVD,75050,141
356325,VALLEY PROTEINS LLC,TX,5601 N MACARTHUR,75038,141
276884,DUNAVANT TRANS GULF TRANSPORTATION LLC,TX,437 INDEPENDENCE PKWY S,77571,141
28070,CODYSUR TRUCKS INC,TX,30351 E BUSINESS 77,78586,141
410483,ROYAL EXPRESS INC,TX,12125 JEF DRIVE,78045,140
367523,RJ LEASING LLC,TX,12283 ROJAS,79936,140
359012,LHOIST NORTH AMERICA,TX,2861 FM 2602,76634-0473,140
33303,EM TRANSPORTATION SERVICES LLC,TX,675 PHIL GRAMM BLVD,77807,140
55266,GENESIS ENDEAVORS LLC,TX,1120 MARVIN A SMITH RD,75662,139
460940,5J OILFIELD TRUCKING LLC,TX,4090 N US HIGHWAY 79,75801,138
24374,PIPELINE SUPPLY & SERVICE LLC,TX,10507 ELLA BLVD STE 100,77038,138
393353,WOOD GROUP USA INC,TX,17325 PARK ROW,77084,138
486155,PURGE RITE LLC,TX,13802 N HIGHWAY 75,77378-3418,136
381471,KBOLA LLC,TX,2600 FM 866,79763-3038,136
560545,BROTHERS PRODUCE INC,TX,3173 PRODUCE ROW,77023,135
484615,SAW TRANSIT LLC,TX,2106 W PIONEER PKWY SUITE 131,76013,135
8596,REVEILLE TRUCKING INC,TX,1615 WILSON RD,78550,134
405358,FRONTIER TANK LINES INC,TX,6850 TPC DR STE 200,75070,134
377849,MEGA CARGO FREIGHT INC,TX,2202 MANANA DR SUITE 124,75220,134
387166,TECHLINE CONSTRUCTION LLC,TX,9609 BECK CIRCLE,78758,134
35489,ENERFLEX ENERGY SYSTEMS INC,TX,10815 TELGE RD,77095,133
167194,UNIVERSTEXAS LLC,TX,9220 CENTRAL EXPRESS,75241,133
90117,AMERICAN TRACK LLC,TX,3950 FOSSIL CREEK BLVD STE106,76137,132
389673,E D C TRANSPORTATION LLC,TX,13023 PELLICANO DR,79928,132
130850,WHITNEY TRANSPORT NORTH AMERICA LLC,TX,9316 US HWY 271 N,75473,132
463316,MUNOZ TRUCKING INC,TX,12460 WEAVER RD,79928,132
129659,2131 TRANSPORTATION LLC,TX,625 SAWYER DR,76179,130
397726,J&M BURNS TRANSPORTATION INC,TX,1400 W COUNTY ROAD 130,79706,130
357030,AUSTIN BRIDGE & ROAD LP,TX,1199 S BELT LINE RD SUITE 110,75019,129
36179,CLEARWELL WELL SERVICES LLC,TX,1250 NE LOOP 410 #1000,78209,129
228426,PREMIER 1 TRUCKING LLC,TX,1301 N STATE HIGHWAY 336,78557,128
560531,TUTLE & TUTLE TRUCKING INC,TX,3672 HWY 67 W,76033,128
44609,FACILITY SOLUTIONS GROUP INC,TX,4401 WESTGATE BLVD #310,78745,127
473209,THE MEN'S WEARHOUSE LLC,TX,10485 W BELLFORT ST,77031,126
467770,MILLER ENVIRONMENTAL SERVICES LLC,TX,401 NAVIGATION BLVD,78408,126
478485,STATEWIDE MATERIALSTRANSPORT LEASING LTD,TX,14411 HWY 290 EAST,78653,126
275946,SHARK TRUCKING INC,TX,12106 MESA DR SUITE A102,77016,126
15746,KEY ENERGY SERVICES LLC,TX,1500 CITYWEST BLVD STE 800,77042,125
428756,GTG TRANSPORTATION LLC,TX,1300 SUMMIT AVENUE SUITE 520,76102,125
220668,ARSH BROTHERS INC.,TX,4700 IRVING BLVD,75247-5708,124
562876,K-3 RESOURCES LP,TX,9458 FM 362,77423,124
328646,SAFA LOGISTICS LLC,TX,4101 VIRIDIAN VILLAGE DR #3318,76005,124
480877,UNIMEX LOGISTICS LLC,TX,700 W ANAYA,78577,124
26647,CAT-SPEC LTD,TX,225 S 16TH ST,77571-4608,124
437360,US MED-EQUIP LLC,TX,7028 GESSNER RD,77040,124
606541,SCOBEY MOVING & STORAGE LTD,TX,9625 BROADWAY,78217,123
250762,B COMM CONSTRUCTORS LLC,TX,11222 IH-10 EAST,78109,122
243463,ELKINS TRUCK LINES LLC,TX,18149 HWY 80 E,75692,121
225795,"CIRCLE 8 CRANE SERVICES, LLC",TX,3174 COUNTY ROAD 48,78380-5945,121
22799,STANDARD SALES COMPANY LP,TX,4800 E 42ND ST,79762-7214,120
266017,PERMIAN BASIN MATERIALS LLC,TX,4044 PENBROOK SUITE 100,79762,120
469774,TRI SUPPLY LLC,TX,7410 EASTEX FREEWAY,77708,120
291195,TALENTO SERVICES LLC,TX,16399 GATEWAY PATH,75078,119
394920,SOUTHERN FLUID SOLUTIONS LLC,TX,1061 COTTON FORD RD,75935,118
594113,HANWHA Q CELLS EPC USA LLC,TX,5051 WESTHEIMER RD SUITE 1900,77056,118
270851,TROY CONSTRUCTION LLC,TX,8521 MCHARD,77053,118
94873,WEST TEXAS CEMENTERS LLC,TX,1400 S JBS PARKWAY,79766,118
357032,BILBO TRANSPORTS INC,TX,2511 EAST PIONEER DR,75061-8920,118
82511,TALKE USA INC,TX,13338 HATCHERVILLE RD GATE 3,77521,117
296313,INDIANA TRANSPORT LLC,TX,402 LOGISTIC DR,78045,116
607638,STERLING CRANE LLC,TX,13727 INTERSTATE 10,77523,116
45572,MPG PIPELINE CONTRACTORS LLC,TX,1271 RAYFORD BEND,77060,116
360103,WILSONART LLC,TX,10535 NW HK DODGEN LOOP,76504,115
376222,AMT EXPRESS LLC,TX,2080 N HIGHWAY 360 SUITE 375,75050,115
379819,BUOYANT ENERGY LLC,TX,3117 E CR 120,79706,115
553284,LITHOTRIPTERS INC,TX,1990 STEAMWAY DRIVE ROUND R,78665,115
64841,MAVERICK EXPRESS CARRIERS LLC,TX,2000 EL INDIO HWY,78852-5452,115
56994,GATEWAY EXPRESS LLC,TX,1768 FM3338,78045,114
298458,WINCO TRUCKING LLC,TX,2671 CR 417,78160,114
70913,DOXA LLC,TX,13740 RESEARCH BLVD SUITE L4,78750,114
506341,FELHER TRANSPORTATION INC,TX,14703 CASSIDY DRIVE,79938,114
382217,TAZ SERVICES LLC,TX,5020 FANNETT ROAD,77705,113
292515,MOONSHINE ENERGY LLC,TX,5006 PORTICO WAY,79707,113
345321,MADASA CARRIERS INC,TX,266 APPALOSA RD,78045,112
22593,MIDTEX OIL LP,TX,3455 IH 35 SOUTH,78132,112
472246,HAZEL'S HOTSHOT INC,TX,14841 DALLAS PKWY STE 525,75254,111
315718,SHOA LOGISTICS LLC,TX,14661 WEST I-20,79763,111
286345,A1 DEDICATED TRANSPORT LLC,TX,2600 SOUTH SHORE BLVD SUITE 300,77573,111
564900,STRIKE OPERATING COMPANY LLC,TX,460 WILDWOOD FOREST DR STE 350 N,77380,111
473641,TSD LOGISTICS INC,TX,7970 HAMPTON ROAD,75503,110
293172,WARRIOR LOGISTICS LLC,TX,450 N FREEPORT PKWY,75019-3508,110
312360,ES EXPRESS LLC,TX,1080 SHADY LN,75650,110
497261,GIBSON & ASSOCIATES INC,TX,11210 RYLIECREST,75180,109
135650,CAPITAL REYES DISTRIBUTING LLC,TX,10095 US HIGHWAY 290 E,78653,109
498149,ROCKING T INC,TX,3300 S FM 1258,79118-7211,109
3329,COWTOWN MATERIALS INC,TX,401 GARDEN ACRES DR,76140,109
392147,SDL CARRIERS INC,TX,22801 MINES ROAD,78045,108
344598,SILVERLEAF LOGISTICS LLC,TX,14810 CALDERON DR,77316,108
548436,VERIZON DELAWARE LLC,TX,700 HIDDEN RIDGE MC HQW0BH50,75038,108
386523,REPUBLIC EES LLC,TX,10613 W SAM HOUSTON PKWY N SUITE 300,77064,107
70859,THE ARBOR EXPERTS LLC,TX,3118 FM 528 #333,77598,107
332487,YUNEX LLC,TX,9225 BEE CAVE RD,78733-6204,106
117375,BARRILLEAUX ENERGY SERVICES LLC,TX,8725 FAWN TRAIL,77385,106
259084,CLASSIC CRANE AND TRANSPORT LP,TX,7007 S FM 1788,79706,106
435320,SPUR FREIGHT SERVICES INC,TX,1100 E HOWARD LN STE 500,78753,106
63122,RANGER ENERGY SERVICES LLC,TX,10350 RICHMOND AVENUE SUITE 550,77042,105
472228,RAMROD TRUCKING INC,TX,3009 HOHL STREET,77093,105
59364,BZ EXPRESS INC,TX,13702 RANKIN PARK DR,77073,105
298018,SHARP OILFIELD SERVICES LLC,TX,3603 FM 51,76240,105
45934,FUSIONSITE TEXAS LLC,TX,3407 CLOVIS RD,79415,104
4292,BEST TRANSPORTATION SERVICE INC,TX,13225 BAY PARK ROAD,77507,104
37099,FRONTIER TRANSPORT NA LP,TX,101 E BARBOURS CUT BLVD,77571,103
391802,RANGER ENERGY EQUIPMENT LLC,TX,10350 RICHMOND AVE,77042-4469,103
231267,CONCENTRIC LLC,TX,1621 W CROSBY RD STE 100,75006,103
255764,RICKY SHULER TRUCKING INC,TX,316 SHELL ROAD,79752,102
397393,HEARTBREAK TRUCKING LLC,TX,149 CR 120,78332,102
368234,SANITATION SOLUTIONS INC,TX,2146 SOUTH CHURCH STREET,75460,102
256727,PANHANDLE EXPRESS LLC,TX,3931 US HWY 60,79045,102
219272,"IM4 TRANSPORT, LLC",TX,4420 VIDAURRI AVE,78041-4079,102
4595,G AND G OPERATORS LTD,TX,907 LIBERAL,79022,101
455572,OPEN ERA LLC,TX,1084 COUNTY ROAD 479,77437-4585,101
343712,MARTIN AG LLC TEXAS,TX,1926 FM 54,79339,101
254735,MAC TRANSPORTATION LLC,TX,395 PRIVATE ROAD 3501,75755,101
24326,DIGCO UTILITY CONSTRUCTION LP,TX,1608 MARGARET ST,77093,101
261614,SAMAX EXPRESS INC,TX,5615 E SAUNDERS ST,78041,100
46894,ANDERSON PERFORATING SERVICES LLC,TX,124 WELCO ROAD,76430,100
377578,SISU ENERGY LLC,TX,2400 HANDLEY EDERVILLE RD,76118,100
2027,TEX-AIR DELIVERY INC,TX,2402 ESTERS BLVD,76051,100
397446,GONCO LOGISTICS LLC,TX,10503 W COUNTY ROAD 72,79707,100
15298,DEE KING TRUCKING LP,TX,17601 E SAINT FRANCIS AVE,79108,100
88627,BLUE JETT TRANSPORT LLC,TX,1007 ANGEL FIRE LN,76001,100
485301,GOODFELLA'S LEASE LLC,TX,1423 BRAZOS DRIVE U5,77320,100
134187,ZEMEN LOGISTICS LLC,TX,2404 HIGH COUNTRY WAY,75025,100
564297,TABET ENTERPRISES INC,TX,12369 PINE SPRINGS DR,79928,99
471242,FORT WORTH CARRIER CORPORATION,TX,4501 N BEACH ST,76137,99
260374,DOUBLE T OILFIELD SERVICE LLC,TX,4707 E COUNTY ROAD 133,79706,99

In [15]:
# Creating a 'Qualified_Prospects.csv' out of our filt_df and valuable columns:
prospect_cols = [
    "LEGAL_NAME",
    "DOT_NUMBER",
    "POWER_UNITS",
    "FLEETSIZE",
    "TOTAL_DRIVERS",
    "PHY_CITY",
    "PHY_STATE",
    "PHY_STREET",
    "PHY_ZIP",
    "PHONE",
    "EMAIL_ADDRESS"
]

qualified_prospects = (filt_df[prospect_cols]) # Save filtered data with another name ('qualified_prospects'), and based on column-specific Series objs 'prospect_cols' info
qualified_prospects.to_csv("Qualified_Prospects.csv", index=False) # .to_csv() method creates a new csv out of the referenced df, and the second argument 'index=False' basically avoids passing an index column to our csv creation